_stripe_bundle_endpoint:
    path: /endpoint/stripe/notify
    defaults: { _controller: StripeBundle:Webhook:notify }

_stripe_bundle_endpoint_dump:
    path: /endpoint/stripe/dump
    defaults: { _controller: StripeBundle:Webhook:dump }
