engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    chacks:
        Naming/LongVariable:
            enabled: false
        Naming/ShortVariable:
            enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- "src/Resources/public/js/jquery.payment/jquery.payment.js"
